# Generated by Django 5.1.1 on 2024-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_oauthtoken_access_token_oauthtoken_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='scope',
        ),
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
