# Generated by Django 5.1.1 on 2024-09-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_oauthtoken_scope_user_has_accepted_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthtoken',
            old_name='refreshh_token',
            new_name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_accepted_terms',
        ),
    ]
