# Generated by Django 5.1.1 on 2024-09-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_refreshh_token_oauthtoken_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='scopes',
            field=models.JSONField(default=list),
        ),
    ]
