# Generated by Django 5.1.1 on 2024-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_oauthtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_hour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='full_day',
            field=models.CharField(choices=[('True', True), ('False', False)], default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='reminders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_hour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
