# Generated by Django 5.1.1 on 2024-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_date_remove_task_time_task_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appellant',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='full_day',
            field=models.BooleanField(),
        ),
    ]
