# Generated by Django 5.1.1 on 2024-09-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_hour',
            field=models.TimeField(null=True),
        ),
    ]
